"""可维护的分析说明条款目录。

这里保存「事实库 -> 分析候选」所需的条款元数据。主流程只负责匹配、
评分和护栏判断，避免把具体案子的规则散落在生成逻辑里。
"""
from __future__ import annotations

from typing import Any


CLAUSE_CATALOG: dict[str, dict[str, Any]] = {
    "disability_hip_joint_replacement_9": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "九级",
        "clause_label": "脊柱、骨盆及四肢损伤：四肢任一大关节行关节假体置换术后",
        "search_terms": ("四肢任一大关节行关节假体置换术后", "关节假体置换术后", "大关节行关节假体"),
    },
    "disability_rib_fractures_6_10": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "十级",
        "clause_label": "颈部及胸部损伤：肋骨骨折6根以上，或者肋骨部分缺失2根以上；肋骨骨折4根以上并后遗2处畸形愈合",
        "search_terms": ("肋骨骨折6根以上", "肋骨部分缺失2根以上", "畸形愈合"),
    },
    "disability_pelvis_deformity_10": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "十级",
        "clause_label": "脊柱、骨盆及四肢损伤：骨盆两处以上骨折或者粉碎性骨折，畸形愈合",
        "search_terms": ("骨盆两处以上骨折或者粉碎性骨折，畸形愈合", "骨盆两处以上骨折", "畸形愈合"),
    },
    "disability_brain_lobectomy_9": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "九级",
        "clause_label": "颅脑、脊髓及周围神经损伤：脑叶部分切除术后",
        "search_terms": ("脑叶部分切除术后", "九级", "颅脑、脊髓及周围神经损伤"),
    },
    "disability_craniotomy_10": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "十级",
        "clause_label": "颅脑、脊髓及周围神经损伤：开颅术后",
        "search_terms": ("开颅术后", "十级", "颅脑、脊髓及周围神经损伤"),
    },
    "disability_brain_softening_10": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "十级",
        "clause_label": "颅脑、脊髓及周围神经损伤：颅脑损伤后遗脑软化灶形成，伴有神经系统症状或者体征",
        "search_terms": ("颅脑损伤后遗脑软化灶形成", "脑软化灶", "神经系统症状或者体征"),
    },
    "disability_tooth_loss_10": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "十级",
        "clause_label": "头面部损伤：牙齿缺失或者折断7枚以上；牙槽骨部分缺损，合并牙齿缺失或者折断4枚以上",
        "search_terms": ("牙齿缺失或者折断7枚以上", "牙槽骨部分缺损", "牙齿缺失或者折断4枚以上"),
    },
    "disability_abdominal_repair_10": {
        "standard_name": "人体损伤致残程度分级",
        "category": "伤残等级",
        "grade": "十级",
        "clause_label": "腹部损伤：肝、脾或者胰腺修补术后；胃、肠或者胆道修补术后；膈肌修补术后",
        "search_terms": ("肝、脾或者胰腺修补术后", "胃、肠或者胆道修补术后", "膈肌修补术后"),
    },
    "period_femoral_neck_fracture_surgery": {
        "standard_name": "人身损害误工期、护理期、营养期评定规范",
        "category": "三期",
        "clause_label": "10.2.8 股骨颈骨折；手术治疗：误工180-365日，护理90-150日，营养90-180日",
        "ranges": {"误工期": "180-365日", "护理期": "90-150日", "营养期": "90-180日"},
        "search_terms": ("股骨颈骨折", "手术治疗：误工180", "护理90", "营养90"),
    },
    "period_tib_fib_open_fracture": {
        "standard_name": "人身损害误工期、护理期、营养期评定规范",
        "category": "三期",
        "clause_label": "10.2.14 胫腓骨骨折；开放性骨折：误工150-180日，护理60-90日，营养60-90日",
        "ranges": {"误工期": "150-180日", "护理期": "60-90日", "营养期": "60-90日"},
        "search_terms": ("10.2.14 胫腓骨骨折", "开放性骨折：误工150", "护理60", "营养60"),
    },
    "period_clavicle_fracture_surgery": {
        "standard_name": "人身损害误工期、护理期、营养期评定规范",
        "category": "三期",
        "clause_label": "10.2.1 锁骨骨折；手术治疗：误工90-120日，护理30-60日，营养60-90日",
        "ranges": {"误工期": "90-120日", "护理期": "30-60日", "营养期": "60-90日"},
        "search_terms": ("10.2.1 锁骨骨折", "手术治疗：误工90", "营养60"),
    },
    "period_scapula_fracture_surgery": {
        "standard_name": "人身损害误工期、护理期、营养期评定规范",
        "category": "三期",
        "clause_label": "10.2.2 肩胛骨骨折；手术治疗：误工90-180日，护理30-60日，营养60-90日",
        "ranges": {"误工期": "90-180日", "护理期": "30-60日", "营养期": "60-90日"},
        "search_terms": ("10.2.2 肩胛骨骨折", "手术治疗：误工90", "营养60"),
    },
    "period_multiple_injuries": {
        "standard_name": "人身损害误工期、护理期、营养期评定规范",
        "category": "三期",
        "clause_label": "附录A.4 多处损伤不能简单累加，应以较长期限为主并结合其他损伤综合考虑",
        "search_terms": ("多处损伤", "不能将多处损伤", "简单累加"),
    },
    "period_upper_limit": {
        "standard_name": "人身损害误工期、护理期、营养期评定规范",
        "category": "三期",
        "clause_label": "附录A.5 受伤后至定残之日前一日的时间已超过误工期上限的，可计算至定残日前一日",
        "search_terms": ("定残之日前一日", "误工期上限", "超过误工期"),
    },
}


INJURY_CANDIDATE_SPECS: tuple[dict[str, Any], ...] = (
    {
        "id": "hip_joint_replacement",
        "title": "髋关节置换术后",
        "category": "伤残等级",
        "include": ("髋关节置换", "全髋关节置换", "半髋关节置换", "人工关节", "股骨头置换", "股骨颈骨折"),
        "require_any": ("置换", "人工关节", "股骨颈"),
        "met_any": ("髋关节置换", "人工关节", "股骨头置换", "全髋"),
        "met_confidence": 92,
        "uncertain_confidence": 70,
        "met_grade": "九级",
        "uncertain_grade": "需核对是否已行关节假体置换",
        "met_suggestion": "可按九级伤残候选处理",
        "uncertain_suggestion": "需核对手术方式和术后影像",
        "met_reason": "病历/手术或术后检查材料提示股骨颈骨折并行髋关节置换，属于四肢大关节假体置换术后。",
        "uncertain_reason": "材料提示髋部重大损伤，但尚需确认是否为关节假体置换术后。",
        "clause_keys": ("disability_hip_joint_replacement_9",),
        "must_mention": ("髋关节置换", "人工关节", "股骨颈骨折"),
    },
    {
        "id": "rib_fractures",
        "title": "多发肋骨骨折",
        "category": "伤残等级",
        "include": ("肋骨骨折", "肋骨陈旧性骨折", "肋骨骨痂", "肋骨畸形愈合"),
        "rule": "rib_count",
        "clause_keys": ("disability_rib_fractures_6_10",),
        "must_mention": ("肋骨骨折",),
    },
    {
        "id": "brain_lobectomy",
        "title": "脑叶部分切除术后",
        "category": "伤残等级",
        "include": ("脑叶部分切除", "脑叶切除", "额叶部分切除", "颞叶部分切除", "顶叶部分切除"),
        "require_any": ("切除", "术后"),
        "met_any": ("脑叶部分切除术后", "脑叶切除术后", "额叶部分切除", "颞叶部分切除", "顶叶部分切除"),
        "met_confidence": 88,
        "uncertain_confidence": 66,
        "met_grade": "九级",
        "uncertain_grade": "需核对是否为脑叶部分切除术后",
        "met_suggestion": "可按九级伤残候选处理",
        "uncertain_suggestion": "需核对手术名称、切除部位及术后影像",
        "met_reason": "材料提示颅脑损伤后行脑叶部分切除，符合九级候选方向。",
        "uncertain_reason": "材料提示颅脑手术或脑叶损伤，但尚需确认是否为脑叶部分切除术后。",
        "clause_keys": ("disability_brain_lobectomy_9",),
        "must_mention": ("脑叶", "切除"),
    },
    {
        "id": "craniotomy",
        "title": "开颅术后",
        "category": "伤残等级",
        "include": ("开颅术后", "开颅手术", "开颅血肿清除", "去骨瓣", "颅骨修补"),
        "require_any": ("开颅", "去骨瓣", "颅骨修补"),
        "met_any": ("开颅术后", "开颅血肿清除术后", "开颅手术后"),
        "met_confidence": 86,
        "uncertain_confidence": 64,
        "met_grade": "十级",
        "uncertain_grade": "需核对是否为开颅术后",
        "met_suggestion": "可按十级伤残候选处理",
        "uncertain_suggestion": "需核对手术记录和术后影像",
        "met_reason": "材料提示颅脑损伤后开颅术后，符合十级候选方向。",
        "uncertain_reason": "材料提示颅脑手术线索，但尚需确认是否达到开颅术后条款条件。",
        "clause_keys": ("disability_craniotomy_10",),
        "must_mention": ("开颅",),
    },
    {
        "id": "brain_softening_neurologic",
        "title": "颅脑损伤后遗脑软化灶",
        "category": "伤残等级",
        "include": ("脑软化灶", "软化灶", "含铁血黄素沉积", "脑挫裂伤后遗"),
        "require_any": ("脑", "颅脑", "挫裂伤", "软化灶"),
        "rule": "brain_softening",
        "clause_keys": ("disability_brain_softening_10",),
        "must_mention": ("脑软化灶", "神经系统"),
    },
    {
        "id": "long_bone_fracture_fixation",
        "title": "四肢长骨/胫腓骨骨折内固定术后",
        "category": "伤残等级",
        "include": ("胫腓骨", "胫骨", "腓骨", "股骨干", "肱骨", "尺桡骨", "长骨", "切开复位内固定", "内固定术后"),
        "require_any": ("骨折", "内固定", "外固定", "钢板", "髓内钉"),
        "rule": "always_uncertain",
        "confidence_any": ("切开复位内固定", "内固定术后", "钢板", "髓内钉", "固定在位"),
        "high_confidence": 70,
        "low_confidence": 58,
        "grade": "需核对功能障碍或畸形愈合",
        "suggestion": "作为重点核对候选；不能仅因骨折内固定直接定级，需结合功能障碍、畸形愈合、骨不连等后果。",
        "reason": "材料提示四肢长骨骨折或内固定治疗，但《人体损伤致残程度分级》通常需进一步核对功能障碍、畸形愈合等后果。",
        "must_mention": ("骨折", "内固定"),
    },
    {
        "id": "pelvis_multiple_fractures",
        "title": "骨盆多发骨折/畸形愈合",
        "category": "伤残等级",
        "include": ("骨盆骨折", "骨盆多发骨折", "耻骨", "坐骨", "骶骨", "骶髂关节", "髋臼"),
        "require_any": ("骨折", "骨痂", "畸形愈合", "分离", "内固定", "外固定"),
        "rule": "pelvis_deformity",
        "clause_keys": ("disability_pelvis_deformity_10",),
        "must_mention": ("骨盆", "骨折"),
    },
    {
        "id": "abdominal_injury",
        "title": "腹部探查及肠系膜/肠壁损伤",
        "category": "伤残等级",
        "include": ("肠系膜", "腹腔探查", "结肠浆膜", "肠修补", "脾破裂", "脾脏"),
        "rule": "always_uncertain",
        "confidence": 58,
        "grade": "需人工核对",
        "suggestion": "仅作为分析时需核对的损伤事实，不自动定级",
        "reason": "病历提示腹部探查及肠系膜或肠壁相关处理，但现阶段缺少稳定的结构化条款映射，且需区分疑似脾破裂与术中实际发现。",
        "must_mention": ("肠系膜", "腹腔探查"),
    },
    {
        "id": "abdominal_organ_repair",
        "title": "腹部脏器/胃肠胆道修补术后",
        "category": "伤残等级",
        "include": ("肝修补", "脾修补", "胰腺修补", "胃修补", "肠修补", "胆道修补", "膈肌修补", "肝破裂修补", "脾破裂修补", "肠破裂修补"),
        "require_any": ("修补", "术后", "手术"),
        "rule": "abdominal_repair",
        "clause_keys": ("disability_abdominal_repair_10",),
        "must_mention": ("修补",),
    },
    {
        "id": "dental_maxillofacial_injury",
        "title": "口腔颌面部/牙齿损伤",
        "category": "伤残等级",
        "include": ("牙缺失", "牙齿缺失", "牙齿脱落", "牙折断", "牙槽骨", "下颌骨", "上颌骨", "口腔"),
        "rule": "dental_count",
        "confidence": 55,
        "grade": "需人工核对",
        "suggestion": "需核对缺牙数量、牙槽骨损伤范围和临床检查",
        "reason": "材料存在牙齿或颌面部损伤线索，但伤残条款通常依赖缺牙数量、牙槽骨损伤范围或功能影响，需人工确认。",
        "clause_keys": ("disability_tooth_loss_10",),
        "must_mention": ("牙", "颌"),
    },
    {
        "id": "dvt_relatedness",
        "title": "下肢深静脉血栓",
        "category": "因果关系/辅助事实",
        "include": ("深静脉血栓", "静脉血栓", "血栓形成"),
        "rule": "always_uncertain",
        "confidence": 45,
        "grade": "不自动作为伤残结论",
        "suggestion": "需结合外伤、制动、既往疾病及临床因果关系判断",
        "reason": "血栓可能与创伤后制动、基础疾病或治疗过程有关，不能仅凭检查报告直接认定为委托事项中的伤残依据。",
        "must_mention": ("血栓",),
    },
)


PERIOD_CANDIDATE_SPECS: tuple[dict[str, Any], ...] = (
    {
        "id": "period_femoral_neck_fracture_surgery",
        "title": "股骨颈骨折手术治疗的误工期、护理期、营养期",
        "include": ("股骨颈骨折", "髋关节置换", "人工关节", "股骨头置换"),
        "confidence": 86,
        "suggestion": "误工期180-365日；护理期90-150日；营养期90-180日，并结合多发损伤综合评定",
        "reason": "材料提示股骨颈骨折并经手术治疗，可作为三期评定的主要损伤之一。",
        "clause_keys": ("period_femoral_neck_fracture_surgery", "period_multiple_injuries", "period_upper_limit"),
    },
    {
        "id": "period_tib_fib_fracture",
        "title": "胫腓骨骨折的误工期、护理期、营养期",
        "include": ("胫腓骨骨折", "开放性胫腓骨", "胫骨骨折", "腓骨骨折", "左胫腓骨", "右胫腓骨"),
        "require_any": ("骨折", "开放性", "内固定", "外固定"),
        "rule": "tib_fib_period",
    },
    {
        "id": "period_clavicle_fracture_surgery",
        "title": "锁骨骨折手术治疗的误工期、护理期、营养期",
        "include": ("锁骨骨折", "锁骨粉碎性骨折", "锁骨内固定", "锁骨切开复位"),
        "require_any": ("锁骨", "骨折"),
        "confidence": 82,
        "suggestion": "手术治疗：误工期90-120日；护理期30-60日；营养期60-90日，并结合多发损伤综合评定",
        "reason": "材料提示锁骨骨折并经手术治疗，可作为三期评定的损伤依据之一。",
        "clause_keys": ("period_clavicle_fracture_surgery", "period_multiple_injuries", "period_upper_limit"),
    },
    {
        "id": "period_scapula_fracture_surgery",
        "title": "肩胛骨骨折手术治疗的误工期、护理期、营养期",
        "include": ("肩胛骨骨折", "肩胛骨粉碎性骨折", "肩胛骨内固定", "肩胛骨切开复位"),
        "require_any": ("肩胛骨", "骨折"),
        "confidence": 82,
        "suggestion": "手术治疗：误工期90-180日；护理期30-60日；营养期60-90日，并结合多发损伤综合评定",
        "reason": "材料提示肩胛骨骨折并经手术治疗，可作为三期评定的损伤依据之一。",
        "clause_keys": ("period_scapula_fracture_surgery", "period_multiple_injuries", "period_upper_limit"),
    },
)
